spring.application.name=Book

spring.datasource.url=jdbc:mysql://localhost:3306/cogni
spring.datasource.username=root
spring.datasource.password=shri@2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true