spring.application.name=Blog-application
spring.datasource.url=jdbc:mysql://localhost:3306/blogp
spring.datasource.username=root
spring.datasource.password=shri@2005
spring.jpa.hibernate.ddl-auto=update